default:
  before_script:
    - source activate base
    - conda activate myjive

stages:
  - test

job_test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - pytest .
    - conda deactivate
  interruptible: true
