image: continuumio/miniconda3:latest

stages:
  - test
  - build

test_code:
  stage: test
  script:
    - echo "Installing environment"
    - conda env create -f ENVIRONMENT.yml
    - source $(conda info --base)/etc/profile.d/conda.sh
    - conda activate myjive
    - echo "Running tests"
    - pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pypi_build:
  stage: build
  script:
    - echo "Installing dev environment"
    - conda env create -f dev/ENVIRONMENT-dev.yml
    - source $(conda info --base)/etc/profile.d/conda.sh
    - conda activate myjive-dev
    - echo "Building wheel file"
    - python -m build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - dist/*.whl  # Save the wheel file as an artifact
    expire_in: 1 week

test_wheel:
  stage: build
  image: python:3.10
  script:
    - echo "Installing cholmod library"
    - apt-get update && apt-get install -y libsuitesparse-dev
    - WHEEL_FILE=$(ls dist/*.whl | head -n 1)
    - echo "Testing installation of wheel file"
    - echo $WHEEL_FILE
    - pip install $WHEEL_FILE
    - echo "Testing myjive imports"
    - python -c "import myjive; print('Successfully imported myjive')"
    - python -c "import myjivex; print('Successfully imported myjivex')"
  needs:
    - pypi_build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

