name: myjive
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.10
  # mandatory packages
  - matplotlib
  - numba
  - numpy<2.0.0 # 2.0.0 breaks compatibility with cholmod
  - pandas
  - scikit-sparse>=0.4.12 # provides cholmod library
  - scipy>=1.12 # 1.12.0 provides scipy.sparse.diags_array
  # support packages
  - pytest
