name: pfem
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.2
  - numpy=1.22.3
  - pip=22.1.2
  - python-gmsh=4.10.3
  - pyqtwebengine=5.15.4
  - scipy=1.8.1
  - spyder=5.2.2
  - pip:
    - pygmsh=7.1.17
