class GlobNames:
    MODEL = "model"
    DOFSPACE = "dofSpace"
    MESHSHAPE = "meshShape"
    MESHRANK = "meshRank"
    COARSEMESH = "coarseMesh"
    ESET = "elemSet"
    NSET = "nodeSet"
    NGROUPS = "nodeGroups"
    EGROUPS = "elemGroups"
    MODELFACTORY = "modelFactory"
    MODULEFACTORY = "moduleFactory"
    SHAPEFACTORY = "shapeFactory"
    SOLVERFACTORY = "solverFactory"
    PRECONFACTORY = "preconFactory"
    TIMESTEP = "timeStep"
    STATE0 = "state0"
    EXTFORCE = "extForce"
    CONSTRAINTS = "constraints"
    OLDSTATE0 = "oldstate0"
    BACKUPSTATE0 = "backupstate0"
    HISTORY = "history"
    MATRIX0 = "matrix0"
    MATRIX2 = "matrix2"
    MATRIXB = "matrixB"
    TABLES = "tables"
    LAMBDA = "lambda"
    MODULEDATA = "module"
    SLIDERS = "sliders"
    ACCEPTED = "accepted"
    LBFACTORS = "lbFactors"
    GP = "gp"
    PRIOR = "prior"
    POSTERIOR = "posterior"
    MEAN = "mean"
    COVARIANCE = "covariance"
    STD = "std"
    LOGLIKELIHOOD = "logLikelihood"
    SAMPLES = "samples"


class PropNames:
    TYPE = "type"


class Actions:
    GETMATRIX0 = "getMatrix0"
    GETMATRIX2 = "getMatrix2"
    GETMATRIXB = "getMatrixB"
    GETMATRIXLB = "getMatrixLB"
    GETUNITMATRIX2 = "getUnitMatrix2"
    GETINTFORCE = "getIntForce"
    GETEXTFORCE = "getExtForce"
    GETUNITFORCE = "getUnitForce"
    GETNEUMANNFORCE = "getNeumannForce"
    CHECKCOMMIT = "checkCommit"
    GETCONSTRAINTS = "getConstraints"
    GETTABLE = "getTable"
    ADVANCE = "advance"


class ParamNames:
    MATRIX0 = "matrix0"
    MATRIX1 = "matrix1"
    MATRIX2 = "matrix2"
    MATRIXB = "matrixB"
    INTFORCE = "intForce"
    EXTFORCE = "extForce"
    UNITFORCE = "unitForce"
    NEUMANNFORCE = "neumannForce"
    CONSTRAINTS = "constraints"
    TABLE = "table"
    TABLENAME = "tableName"
    TABLEWEIGHTS = "tableWeights"
    SOLUTION = "solution"
    UNITMATRIX = "unitMatrix"
    RHO = "rho"
    AREA = "area"
    YOUNG = "young"
    SPRING = "spring"
    LOAD = "load"
    VERBOSE = "verbose"


class GPActions:
    CONFIGUREFEM = "configureFEM"
    CONFIGUREPRIOR = "configurePrior"
    GETPRIORMEAN = "getPriorMean"
    GETPRIORCOVARIANCE = "getPriorCovariance"
    GETPOSTERIORMEAN = "getPosteriorMean"
    GETPOSTERIORCOVARIANCE = "getPosteriorCovariance"
    GETPRIORSAMPLES = "getPriorSamples"
    GETPOSTERIORSAMPLES = "getPosteriorSamples"
    GETLOGLIKELIHOOD = "getLogLikelihood"
    KALMANUPDATE = "kalmanUpdate"
    PROJECTSAMPLES = "projectSamples"


class GPParamNames:
    FIELD = "field"
    PRIORMEAN = "priorMean"
    PRIORCOVARIANCE = "priorCovariance"
    POSTERIORMEAN = "posteriorMean"
    POSTERIORCOVARIANCE = "posteriorCovariance"
    PRIORSAMPLES = "priorSamples"
    POSTERIORSAMPLES = "posteriorSamples"
    LOGLIKELIHOOD = "logLikelihood"
    FULLCOVARIANCE = "fullCovariance"
    NSAMPLE = "nsamples"
    SEED = "seed"
    RNG = "randomNumberGenerator"
