name: myjive-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.10
  # mandatory packages
  - matplotlib=3.5.2
  - numba=0.56.4
  - numpy=1.23.5
  - pandas=2.2.2
  - seaborn=0.13.2
  - scikit-sparse=0.4.12 # provides cholmod library
  - scipy>=1.12.0 # provides scipy.sparse.diags_array
  # support packages
  - black
  - grayskull
  - pytest
  - twine
